name: 🚀 Deploy Exchange Rate Calculator APP

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  #  pull_request:
  #    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "SFTP"
  deploy-via-sftp:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # To get the ssh_private_key get it from /Users/ivan/.ssh/id_rsa for user imoyano
      - uses: actions/checkout@v2

      - name: 🚀 SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.1
        with:
          username: ${{ secrets.SSH_USERNAME }}
          server: opal8.opalstack.com
          port: 22 # default is 22
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}

          # will put all file under this path
          local_path: ./* # default is ./*
          # files will copy to under remote_path
          remote_path: /home/imoyano/apps/xrc_elixir

          # sftp args
          args: '-o ConnectTimeout=5'

      - name: 💻 Rebooting SCM 👾👾👾
        uses: appleboy/ssh-action@master
        with:
          host: opal8.opalstack.com
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/imoyano/apps/xrc_elixir/xrc_api
            mix ecto.migrate
            cd /home/imoyano/apps/xrc_elixir
            sh start.sh
            ls -al